Draft overview page
UTNkar/registration-system pull request #26
Opened 2020-10-27 19:09 UTC by lshoravi

Changes a couple of things:
1. Slightly changes the user models
2. Removes old migrations that are no longer needed.
3. Adds an incomplete overview page

2020-11-12 19:02 UTC, lshoravi commented on registrationSystem/registrationSystem/views.py
> +    user = user_model.objects.get(id=2)
Yes, it will be changed when the page is actually redirected to.

2020-11-19 17:38 UTC, dakaza98 requested changes

2020-11-19 17:38 UTC, dakaza98 commented on registrationSystem/registrationSystem/models.py
> +        return user
These functions are very similar. Create a function for the similar behaviour

2020-11-19 17:38 UTC, dakaza98 commented on registrationSystem/registrationSystem/views.py
> +    user_id = 2  # temp
You should be able to use request.user for this. You should also be able to add the login_required decorator https://docs.djangoproject.com/en/3.1/topics/auth/default/#the-login-required-decorator

2020-11-19 18:28 UTC, dakaza98 approved these changes

2020-11-19 18:28 UTC, merged