Feat/admin raffle control
UTNkar/registration-system pull request #51
Opened 2020-11-21 12:37 UTC by Maxxen

This PR does not really contain a "complete" feature, but I think it is best to get a basic implementation in the dev branch so other tasks can query the raffle state when implementing views.

Informal changelog:
* Renamed InterestCheck to RaffleEntry
* Added basic RiverRaftingRaffleState singleton model (and abstract superclass) that can be queried for the current raffle state
* Added initial skeleton implementation of raffle controls in admin panel 
  - Further development blocked since RiverRafting management has not decided on how the raffle should treat (non-)UTN-members.
  - "idiot-proofing" the admin UX probably requires more thinking and is not super relevant right now

* Started refactor of models.py into separate modules
  - Eventually the model names should be event agnostic and only be separated through module namespacing/conditional imports

* Remove plural from EmailConfirmations

2020-11-21 14:25 UTC, dakaza98 requested changes

2020-11-21 14:25 UTC, dakaza98 commented on src/registrationSystem/admin.py
> +        return HttpResponseRedirect("../")
Where does "../" take you?

2020-11-21 14:25 UTC, dakaza98 commented on src/registrationSystem/admin.py
> +        return HttpResponseRedirect("../")
Where does "../" take you?

2020-11-21 14:25 UTC, dakaza98 commented on src/registrationSystem/models/river_rafting/__init__.py
> +from .email_confirmation import EmailConfirmation
You import many classes but you don't use them

2020-11-21 14:25 UTC, dakaza98 commented on src/registrationSystem/models/river_rafting/raffle_entry.py
> +    """Interest checks start out as unconfirmed, and once the mail has
Rename intrest checks to raffly entry. Check in the rest of the documentation as well

2020-11-21 14:25 UTC, dakaza98 commented on tools/generate-models.py
> +import os
Is this script still needed?

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/admin.py
> +@admin.register(RiverRaftingRaffleState)
The models should only be registered if `settings.EVENT == 'Riverrafting'` as to allow other events to only register what's important.

Furthermore, should there not be a generic/abstract raffle model and a way to set which implementation to use, as we do with user models and `get_user_model()`? @dakaza98

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/admin.py
> +@admin.register(RiverRaftingRaffleState)
Suggested is to move the registration to __init__.py

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/models/__init__.py
> +)
Good idea to separate river rafting components, but is EmailConfirmation not common?

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/models/river_rafting/__init__.py
> +    admin.site.register(RiverRaftingTeam)
Refering to other review comment, choose what admin models to register here

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/models/__init__.py
> +)
Same with RaffleEntry

2020-11-21 14:27 UTC, lshoravi commented on src/registrationSystem/models/river_rafting/river_rafting_raffle_state.py
> +    state = models.CharField(max_length=20, choices=CHOICES)
Nice!

2020-11-21 15:57 UTC, Maxxen commented on src/registrationSystem/admin.py
> +@admin.register(RiverRaftingRaffleState)
Right. Registration of models and decoupling between river rafting/common models is not clearly defined, and this PR makes a half assed job of it. I agree that we should perform some sort of conditional importing/registration and that RaffleEntry/EmailResponse should be event-agnostic, but it is not clear how this should work in practice (Inheritance, duck-typing, separate instances altogheter?), and judging from the their use in views and forms, it looks like they are already tightly coupled. When I spoke to Daniel before merging we agreed that it would be best to keep them as is and part of the RR-module.

It might be out of scope for this PR, but I could look into abstraction layers/decoupling them if we can come up with a plan.

2020-11-21 15:59 UTC, Maxxen commented on src/registrationSystem/admin.py
> +@admin.register(RiverRaftingRaffleState)
Ok above response was more suited to the other comments regarding home of EmailConfirmation model. Ill fix admin registration.

2020-11-21 16:04 UTC, Maxxen commented on tools/generate-models.py
> +import os
Yes, why? I think it is/will still be useful when testing the raffle mechanism / recreating the database

2020-11-21 16:07 UTC, Maxxen commented on src/registrationSystem/models/river_rafting/__init__.py
> +from .email_confirmation import EmailConfirmation
I import them to bring them into the module scope. Is this not good practice? Once we actually decouple RR models from common/other events they should not be imported in the models scope, so that they are accessed only through the `models.river_rafting` namespace.

2020-11-21 17:18 UTC, Maxxen commented on src/registrationSystem/admin.py
> +        return HttpResponseRedirect("../")
Up one step.

2020-11-21 17:34 UTC, dakaza98 commented on src/registrationSystem/models/river_rafting/__init__.py
> +from .email_confirmation import EmailConfirmation
ah okey

2020-11-21 17:35 UTC, dakaza98 commented on tools/generate-models.py
> +import os
aight

2020-11-22 10:20 UTC, dakaza98 approved these changes

2020-11-22 10:20 UTC, merged