Feat/team invite link
UTNkar/registration-system pull request #56
Opened 2020-11-22 18:55 UTC by Maxxen

Closes #43 

Also includes misc fixes and tweaks to account creation / overview page / login views.

2020-11-23 12:50 UTC, dakaza98 requested changes

2020-11-23 12:50 UTC, dakaza98 commented on src/registrationSystem/views.py
> +            print(form.errors.items())
You can remove these prints

2020-11-23 12:50 UTC, dakaza98 commented on src/registrationSystem/views.py
> +
It would be good to add a guard so that if you already belong to a team, you can not join the team

2020-11-24 17:29 UTC, lshoravi requested changes
Small comments- see below

2020-11-24 17:29 UTC, lshoravi commented on src/registrationSystem/forms.py
> +            'person_nr': TextInput(),
I believe TextInput wont give validation here- shouldn't it be PersonNumberInput?

2020-11-24 17:29 UTC, lshoravi commented on src/registrationSystem/forms.py
> +            'person_nr': TextInput(),
https://github.com/UTNkar/registration-system/blob/development/src/registrationSystem/fields.py

2020-11-24 17:29 UTC, lshoravi commented on src/registrationSystem/views.py
> +        return HttpResponse('Unauthorized', status=401)
Could you clarify this comment?

2020-11-24 17:29 UTC, lshoravi commented on src/registrationSystem/views.py
> +            team = RiverRaftingTeam.objects.create(leader=leader)
TODO: Use team model depending on environment variables

2020-11-26 17:08 UTC, merged